version: '3'

services:
  ml-api:
    image: dinuka07/rp-project/ml-api-image:latest
    build: ./ml_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    # volumes:
    #   - ml-api-data:/app/data
    networks:
      - private 
      - public

  backend:
    image: dinuka07/rp-project/main-api-image:latest
    build: ./main_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - ml-api
      - redis
    networks:
      - private 
      - public

  frontend:
    image: dinuka07/rp-project/web-app-image:latest
    build: ./web_app
    ports:
      - "3001:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - private 
      - public

  # admin:
  #   image: dinuka07/rp-project/web-admin-image:latest
  #   build: ./web_admin
  #   ports:
  #     - "3003:3003"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend
  #   networks:
  #     - private 
  #     - public

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - private
      - public 

volumes:
  # ml-api-data:
  redis-data:

networks:
  public: 
  private: 
    internal: true